language: go
go:
- 1.5
- tip
install:
  - go get github.com/constabulary/gb/...
  - go get github.com/golang/lint/golint
before_script:
  - gb vendor restore
script: 
  - gb test
  - go tool vet src/
  - golint src/
before_deploy:
  - GOARCH=arm GOOS=linux gb build
  - GOARCH=386 GOOS=linux gb build
  - GOARCH=amd64 GOOS=linux gb build

deploy:
  provider: releases
  api_key:
    secure: use `travis setup releases` to setup this key
  file: bin/*
  file_glob: true
  on:
    repo: AcalephStorage/spriteful
    tags: true
    go: 1.5
