language: go
go:
- tip
install:
  - go get github.com/constabulary/gb/...
  - go get github.com/golang/lint/golint
before_script:
script: 
  - make clean deps build 
  - go tool vet src/
  - golint src/
before_deploy:
  - GOARCH=arm GOOS=linux gb build
  - GOARCH=386 GOOS=linux gb build
  - GOARCH=amd64 GOOS=linux gb build

deploy:
  provider: releases
  api_key:
    secure: "udDyfx7HqHaXAkqY5xiR1NoOElQ6+OS0TQixTPNI6em4+FECxWO3DoMokgicWDGKBUKsFoSYXfxxZW1X+jOcShSr0FNGJ2RoTm1mESNsVgXsRZwpayy0PNH7I5m6t2MegM2ai36Ahc3yIlkjkS9Yw1Fd/WdruPhI0pVEpdhSFDI9uabxPxmN5ZIvFuLJ45lVdI0WguZ0gEalw2xov5yz2N7xcHpv1TVMfYRftCI/WkCLvo6i/rQtJm/sACVT/Wv9usH4rC3WQYfTfKapSxTY80rv9y7RVaSJbBu5xQ+zS3st0rAIr0NX1jvqCcovtr4LWyHKAQkpgmIErTw/ru++0EO70y8mPq7pTsXi3ulqnfW8XWsXH6cnDZJ3GUIJbP9OuSN+wH2d1vJT1NxEcskq8XZYmqulqDwCywNOHRXdCo4uXmQgQ40yNjQv1Dm8K4vA45rtEBeu0RKUuXXDPhktgDDSYOSGEztki+pNSw3raqby6o8OLlMH4PhfTxoE8vqLvB7p/lpV/IcODikKqU//D47tkBSStf1NuBMqR48bNee40rXJcx4wn3QCG6jVYQQOnVJ3QzGbDVDVYUpr6GwP0CHDfvRNmdB/blefviE4wedOXBq7YrFev5t8ByO332jkBjMBRRM29msUPWOzijd/A3ikC++kisaPn7CKGQw1NMc="
  file: bin/*
  file_glob: true
  on:
    repo: AcalephStorage/spriteful
    tags: true
